import { 
  API_BASE_URL, 
  ACCOUNT_ENDPOINT, 
  PROJECTS_ENDPOINT, 
  CAPABILITIES_ENDPOINT, 
  CAPABILITIES_TAGS_ENDPOINT, 
  PROJECTS_TAGS_ENDPOINT, 
  PLATFORMS_ENDPOINT 
} from "@/apiConfig";

export const ACCOUNT_API = `${API_BASE_URL}${ACCOUNT_ENDPOINT}`;
export const PROJECTS_API = `${API_BASE_URL}${PROJECTS_ENDPOINT}`;
export const CAPABILITIES_API = `${API_BASE_URL}${CAPABILITIES_ENDPOINT}`;
export const CAPABILITIES_TAGS_API = `${API_BASE_URL}${CAPABILITIES_TAGS_ENDPOINT}`;
export const PROJECTS_TAGS_API = `${API_BASE_URL}${PROJECTS_TAGS_ENDPOINT}`;
export const PLATFORMS_API = `${API_BASE_URL}${PLATFORMS_ENDPOINT}`;